---
- hosts: ycslerm
  remote_user: root
 
  tasks:

  - name: Create user account 
    user:
      name: user1
      shell: /bin/bash

  - name: Read variables
    include_vars: '{{ item }}'
    with_first_found:
      - files:
          - "{{ inventory_hostname }}.yml"
          - "default.yml"
        paths: "vars/"

  - name: Deploy SSH-Keys to remote host
    authorized_key:
      user: user1
      key: "{{ keytodeploy|map(attribute='sshkey')|join('\n') }}"
      exclusive: true
